Update LPSolve instructions for homebrew.
Turns out `homebrew/science` has been deprecated, when trying to install I get 
```
➜ brew tap homebrew/science
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```
We can use `brewsci/science` instead as `lp_solve` doesn't appear to have been migrated into the primary repo.